### PR TITLE
Added Ruby Code.

### PR DESCRIPTION
**Pull request by puyogo-suzuki**
Please merge!

### CODE REVIEW

**Comment by WasshoiSugi** [comment]
Add comment.

**Comment by WasshoiSugi** [comment]
スペルミス直してちょーだい★

**Comment by puyogo-suzuki** [comment]
Where?

**Comment by puyogo-suzuki** [comment]
Oh, I got it.
I made spell miss 'variance' as 'variant'.

**Comment by WasshoiSugi** [comment]
えーやん。流石やん。

**Pull request merged**
